---
# Codacy configuration for BabelFishAI
# Excludes files from metric analysis where complexity is acceptable

engines:
  # Exclude files from cyclomatic complexity / method length analysis
  metrics:
    exclude_paths:
      - "src/pages/options/options.js"  # UI multi-provider requires inherent complexity
      - "src/utils/providers.js"         # Provider config definitions

  # ESLint configuration - exclude files with intentionally unused functions
  eslint-8:
    enabled: true
    exclude_paths:
      - "src/utils/ui.js"  # Contains reserved functions for future use

  # Exclude focus-utils from security false positive (HTML in replaceAll)
  eslint-security:
    exclude_paths:
      - "src/utils/focus-utils.js"

# Global exclusions
exclude_paths:
  - "node_modules/**"
  - "**/*.min.js"
  - "vendor/**"
